# Generated by Django 4.1.7 on 2023-02-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veo_company_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veo_company_structure.node'),
        ),
    ]
