# Generated by Django 4.1.7 on 2023-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veo_company_structure', '0002_alter_node_height_alter_node_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
    ]
